name: Generate badge

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * mon"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate badge
      run: |
        mkdir generated
        python main.py ${{ secrets.LEETCODE_USERNAME }}
        
    - name: Update repo if needed
      run: |
        git config --global user.name "github actions"
        git config --global user.email "noreply@example.com"
        git switch github-actions
        mv generated/badge.png badge.png
        git add badge.png
        git commit -m "chore: update badge" && git push || true